using Content.Client.CrewManifest;
using Content.Client.GameTicking.Managers;
using Content.Client.Lobby;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.UserInterface.Controls;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Console;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Numerics;

namespace Content.Client._Sunrise.Latejoin;

[GenerateTypedNameReferences]
public sealed partial class SRLateJoinGui : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IConsoleHost _consoleHost = default!;
    [Dependency] private readonly JobRequirementsManager _playManager = default!;
    [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;

    private ClientGameTicker _gameTicker;

    private NetEntity _lastSelection;

    private readonly Dictionary<string, BoxContainer> _jobCategories;
    private readonly Dictionary<string, SRLateJoinJobButton> _buttons = new();

    // Dropdown state: stores the dropdown container per job and tracks which one is open.
    private readonly Dictionary<string, BoxContainer> _dropdowns = new();
    private string? _expandedJobId;

    public SRLateJoinGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _gameTicker = EntitySystem.Get<ClientGameTicker>();
        _gameTicker.LobbyJobsAvailableUpdated += UpdateUi;

        _jobCategories = new Dictionary<string, BoxContainer>();
        StationSelection.StationsItemList.OnItemSelected += args =>
        {
            UpdateUi(_gameTicker.JobsAvailable);
        };
        CrewManifestButton.OnPressed += _ =>
        {
            EntitySystem.Get<CrewManifestSystem>().RequestCrewManifest(_lastSelection);
        };

        _lastSelection = _gameTicker.JobsAvailable.Keys.FirstOrNull() ?? NetEntity.Invalid;

        UpdateUi(_gameTicker.JobsAvailable);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _gameTicker.LobbyJobsAvailableUpdated -= UpdateUi;
    }

    public void UpdateUi(IReadOnlyDictionary<NetEntity, Dictionary<ProtoId<JobPrototype>, int?>> obj)
    {
        if (StationSelection.Selected is null)
        {
            CrewManifestButton.Visible = false;
            return;
        }

        CrewManifestButton.Visible = true;

        var station = StationSelection.Selected.Value;
        var jobs = obj[station];

        if (station != _lastSelection)
        {
            // Buttons and dropdowns are children of category containers, so removing
            // the category containers from JobList is sufficient to clean everything up.
            foreach (var (_, box) in _jobCategories)
            {
                JobList.RemoveChild(box);
            }
            _buttons.Clear();
            _dropdowns.Clear();
            _expandedJobId = null;
            _jobCategories.Clear();
        }

        _lastSelection = station;

        var departments = new List<DepartmentPrototype>();
        foreach (var department in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
        {
            if (department.EditorHidden)
                continue;

            departments.Add(department);
        }

        departments.Sort(DepartmentUIComparer.Instance);

        foreach (var department in departments)
        {
            var departmentName = Loc.GetString($"department-{department.ID}");

            var hasRole = false;
            foreach (var (jobId, _) in jobs)
            {
                if (department.Roles.Contains(jobId))
                {
                    hasRole = true;
                    break;
                }
            }

            if (!hasRole)
            {
                continue;
            }

            if (!_jobCategories.TryGetValue(department.ID, out var category))
            {
                category = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Name = department.ID,
                    ToolTip = Loc.GetString("humanoid-profile-editor-jobs-amount-in-department-tooltip",
                        ("departmentName", departmentName))
                };

                var departamentLabel = new Label
                {
                    Text = Loc.GetString("humanoid-profile-editor-department-jobs-label",
                        ("departmentName", departmentName)),
                    Margin = new Thickness(5f, 0, 0, 0)
                };

                category.AddChild(new StripeBack()
                {
                    Visible = true,
                    HorizontalExpand = true,
                    HasMargins = true,
                    MouseFilter = MouseFilterMode.Stop,
                    Children =
                    {
                        departamentLabel
                    }
                });

                _jobCategories[department.ID] = category;
                JobList.AddChild(category);
            }

            foreach (var (jobId, _) in jobs)
            {
                if (!department.Roles.Contains(jobId))
                    continue;

                if (_buttons.ContainsKey(jobId))
                    continue;

                var job = _prototypeManager.Index(jobId);

                var newButton = new SRLateJoinJobButton(station, jobId, _gameTicker, _prototypeManager);

                var isAllowed = true;
                if (!_playManager.IsAllowed(
                    job,
                    (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                    out var denyReason))
                {
                    isAllowed = false;
                    newButton.Disabled = true;
                    newButton.ToolTip = denyReason.ToString();
                }

                // Always add the main button first so it appears even if dropdown building fails.
                category.AddChild(newButton);
                _buttons[jobId] = newButton;

                if (job.AlternativeNames.Count == 0)
                {
                    // No alternatives: click directly joins.
                    newButton.OnPressed += _ =>
                    {
                        Logger.InfoS("latejoin", $"Late joining as ID: {jobId}");
                        _consoleHost.ExecuteCommand($"joingame {CommandParsing.Escape(jobId)} {station}");
                        Close();
                    };
                }
                else
                {
                    // Has alternatives: click toggles a dropdown with name choices.
                    newButton.ToggleMode = true;
                    newButton.OnPressed += _ => ToggleDropdown(jobId);

                    // Build the dropdown panel (hidden by default).
                    var dropdown = BuildNameDropdown(job, jobId, station);
                    if (!isAllowed)
                    {
                        // Disable all name choice buttons if the job itself is locked.
                        foreach (var child in dropdown.Children)
                        {
                            if (child is Button btn)
                                btn.Disabled = true;
                        }
                    }

                    category.AddChild(dropdown);
                    _dropdowns[jobId] = dropdown;
                }
            }
        }
    }

    /// <summary>
    /// Builds a dropdown container with buttons for the job's main name and all alternative names.
    /// </summary>
    private BoxContainer BuildNameDropdown(JobPrototype job, string jobId, NetEntity station)
    {
        var dropdown = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Visible = false,
            Margin = new Thickness(16, 0, 0, 0),
        };

        // Main name button.
        dropdown.AddChild(CreateNameChoiceButton(job.Icon, job.LocalizedName, jobId, station, null));

        // Alternative name buttons.
        foreach (var alt in job.AlternativeNames)
        {
            var iconId = alt.Icon ?? job.Icon;
            dropdown.AddChild(CreateNameChoiceButton(iconId, alt.LocalizedName, jobId, station, alt.Name));
        }

        return dropdown;
    }

    /// <summary>
    /// Creates a single name-choice button inside a dropdown.
    /// </summary>
    private Button CreateNameChoiceButton(
        ProtoId<JobIconPrototype> iconId,
        string displayName,
        string jobId,
        NetEntity station,
        string? altKey)
    {
        var btn = new Button
        {
            HorizontalExpand = true,
        };

        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
        };

        var icon = new TextureRect
        {
            TextureScale = new Vector2(2, 2),
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 4, 0),
        };

        if (_prototypeManager.TryIndex(iconId, out JobIconPrototype? jobIconProto))
            icon.Texture = jobIconProto.Icon.Frame0();

        var label = new Label
        {
            Text = displayName,
            Margin = new Thickness(2, 0),
        };

        container.AddChild(icon);
        container.AddChild(label);
        btn.AddChild(container);

        btn.OnPressed += _ =>
        {
            var cmd = altKey != null
                ? $"joingame {CommandParsing.Escape(jobId)} {station} {CommandParsing.Escape(altKey)}"
                : $"joingame {CommandParsing.Escape(jobId)} {station}";
            Logger.InfoS("latejoin", $"Late joining as ID: {jobId} display: {displayName}");
            _consoleHost.ExecuteCommand(cmd);
            Close();
        };

        return btn;
    }

    /// <summary>
    /// Toggles the dropdown for the given job. Closes any previously open dropdown.
    /// </summary>
    private void ToggleDropdown(string jobId)
    {
        if (_expandedJobId == jobId)
        {
            // Collapse current dropdown.
            if (_dropdowns.TryGetValue(jobId, out var dd))
                dd.Visible = false;
            if (_buttons.TryGetValue(jobId, out var curBtn))
                curBtn.Pressed = false;
            _expandedJobId = null;
        }
        else
        {
            // Collapse previous dropdown and reset its button state.
            if (_expandedJobId != null)
            {
                if (_dropdowns.TryGetValue(_expandedJobId, out var prevDd))
                    prevDd.Visible = false;
                if (_buttons.TryGetValue(_expandedJobId, out var prevBtn))
                    prevBtn.Pressed = false;
            }

            // Expand new dropdown.
            if (_dropdowns.TryGetValue(jobId, out var newDd))
                newDd.Visible = true;
            if (_buttons.TryGetValue(jobId, out var newBtn))
                newBtn.Pressed = true;

            _expandedJobId = jobId;
        }
    }
}
