using Content.Client.GameTicking.Managers;
using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunrise.Latejoin;

[GenerateTypedNameReferences]
public sealed partial class SRLateJoinJobButton : Button
{
    private readonly IPrototypeManager _prototypeManager;
    private readonly ClientGameTicker _gameTicker;
    private readonly NetEntity _station;
    private readonly string _jobId;
    private readonly string? _displayName;
    private readonly ProtoId<JobIconPrototype>? _displayIcon;

    /// <summary>
    /// Creates a job button. If <paramref name="displayName"/> or <paramref name="displayIcon"/> are provided,
    /// they override the job's default name and icon (used for alternative job names).
    /// </summary>
    public SRLateJoinJobButton(
        NetEntity station,
        string jobId,
        ClientGameTicker gameTicker,
        IPrototypeManager prototypeManager,
        string? displayName = null,
        ProtoId<JobIconPrototype>? displayIcon = null)
    {
        RobustXamlLoader.Load(this);
        _prototypeManager = prototypeManager;
        _gameTicker = gameTicker;
        _station = station;
        _jobId = jobId;
        _displayName = displayName;
        _displayIcon = displayIcon;

        _gameTicker.LobbyJobsAvailableUpdated += UpdateButton;
        UpdateButton(_gameTicker.JobsAvailable);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _gameTicker.LobbyJobsAvailableUpdated -= UpdateButton;
    }

    private void UpdateButton(IReadOnlyDictionary<NetEntity, Dictionary<ProtoId<JobPrototype>, int?>> obj)
    {
        if (!obj.ContainsKey(_station) || !obj[_station].ContainsKey(_jobId))
        {
            Visible = false;
            return;
        }

        var prototype = _prototypeManager.Index<JobPrototype>(_jobId);

        var iconId = _displayIcon ?? prototype.Icon;
        var jobIcon = _prototypeManager.Index(iconId);
        JobIcon.Texture = jobIcon.Icon.Frame0();

        var name = _displayName ?? prototype.LocalizedName;
        JobText.Text = $"{name} ({obj[_station][_jobId]?.ToString() ?? "Unlimited"})";

        Disabled = obj[_station][_jobId] == 0;
    }
}
